# SITE CONFIGURATION
title: Data Science Data # your site title
author: Sheikh Hanif # You :P
description: > # Meta description of Homepage
  Data Science Data is an ideal platform to learn and get free resources about data science, 
  ML, Deep learning and NLP.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://datasciencedata.com" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Data Science - Data
  links:
    # - https://twitter.com/BenBalter
    - https://www.facebook.com/groups/1783416061775380/
    - https://www.facebook.com/Data-Science-Data-826265831048759/
    - https://www.linkedin.com/in/sheikhhanif
    #- https://plus.google.com/+BenBalter
    - https://github.com/sheikhhanif
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Data Science', link: '/data-science'}
  - {name: 'Machine Learning', link: '/machine-learning'}
  - {name: 'Programming', link: '/programming'}
  #- {name: 'Resources', link: '/learning-resource'}
  #- {name: 'News', link: '/news'}
  - {name: 'Contact', link: '/contact'}
  
tagline: >
  Start Your Data Science Journey

hero_img: datascience.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: ict_hanif@yahoo.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  sheikhhanif
linkedin_username: sheikhhanif
facebook_username: 1783416061775380 
youtube_username: geeklesson
disqus:
  shortname: datasciencedata # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - Jekyll-paginate

paginate: 6
